apiVersion: v1
kind: ConfigMap

metadata:
  name: mysql-init-script
  namespace: nagp

data:
  mysql-init.sql: |
    CREATE DATABASE IF NOT EXISTS employee_db;

    USE employee_db;

    CREATE TABLE IF NOT EXISTS employees (
      id INT PRIMARY KEY,
      name VARCHAR(50),
      department VARCHAR(50)
    );

    INSERT IGNORE INTO employees VALUES
    (1,'John','IT'),
    (2,'Sam','HR'),
    (3,'Raj','Finance'),
    (4,'Neha','Sales'),
    (5,'Amit','Operations');
